// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMup-JsDdkZDTk63pt2BHXqzYA9r-lgIo',
    appId: '1:956912794113:web:294dcd64d424c913a8de00',
    messagingSenderId: '956912794113',
    projectId: 'matrixgym-81d6f',
    authDomain: 'matrixgym-81d6f.firebaseapp.com',
    storageBucket: 'matrixgym-81d6f.firebasestorage.app',
    measurementId: 'G-6Q8KKD0R6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCJORVVlysUWKIhKMbI6ytbX3cVeDLDxs',
    appId: '1:956912794113:android:c9d7c108874e5c21a8de00',
    messagingSenderId: '956912794113',
    projectId: 'matrixgym-81d6f',
    storageBucket: 'matrixgym-81d6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAirFqI_xbVSia7q4pBRY1Jz4OoUl5XuJA',
    appId: '1:956912794113:ios:036c779644963605a8de00',
    messagingSenderId: '956912794113',
    projectId: 'matrixgym-81d6f',
    storageBucket: 'matrixgym-81d6f.firebasestorage.app',
    iosBundleId: 'com.example.matrixgym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAirFqI_xbVSia7q4pBRY1Jz4OoUl5XuJA',
    appId: '1:956912794113:ios:036c779644963605a8de00',
    messagingSenderId: '956912794113',
    projectId: 'matrixgym-81d6f',
    storageBucket: 'matrixgym-81d6f.firebasestorage.app',
    iosBundleId: 'com.example.matrixgym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMup-JsDdkZDTk63pt2BHXqzYA9r-lgIo',
    appId: '1:956912794113:web:169dcd4e82099503a8de00',
    messagingSenderId: '956912794113',
    projectId: 'matrixgym-81d6f',
    authDomain: 'matrixgym-81d6f.firebaseapp.com',
    storageBucket: 'matrixgym-81d6f.firebasestorage.app',
    measurementId: 'G-QHYESX13D9',
  );
}
